// Code generated by "stringer -linecomment -type LayerKind"; DO NOT EDIT.

package assets

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LayerKindBackground-1]
	_ = x[LayerKindBackgroundSmall-2]
	_ = x[LayerKindNormal-3]
	_ = x[LayerKindHeight-4]
	_ = x[LayerKindAS-5]
}

const _LayerKind_name = "BKGBKGSMNMHGTAS"

var _LayerKind_index = [...]uint8{0, 3, 8, 10, 13, 15}

func (i LayerKind) String() string {
	i -= 1
	if i >= LayerKind(len(_LayerKind_index)-1) {
		return "LayerKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _LayerKind_name[_LayerKind_index[i]:_LayerKind_index[i+1]]
}
